/**
 * TypeScript declaration augmentation for Express types
 * Extends Express Request interface with custom properties
 */

declare namespace Express {
  /**
   * Augmented Request interface with additional properties
   */
  export interface Request {
    /**
     * Optional request correlation ID for tracking requests across logs
     * Generated by middleware if not present
     */
    id?: string;
  }
}
