# FUNDING options
# Uncomment and set your sponsor handles
# github: [csmat]
# patreon: your-handle
# open_collective: your-collective
# ko_fi: your-handle
# tidelift: your-package
# custom: ["https://your-sponsor-page.example.com"]
