name: Feature request
description: Suggest an idea or improvement
labels: [enhancement]
body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: Describe the feature and the problem it solves
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposal
      description: Outline the solution, UX, and constraints
    validations:
      required: true
  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance criteria
      description: Define success conditions and edge cases
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Mention other approaches and trade-offs
